version: '3.3'

services:
  streamlit_modelling:
    container_name: streamlit-multistage
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: streamlit-multistage:0.1.0
    ports:
      - '8502:8502'
    volumes:
      - './data:/usr/src/app/data:delegated'
      - './project:/usr/src/app/project:delegated'
      - './images:/usr/src/app/images:delegated'
      - '../drjobel:/usr/src/app/drjobel:delegated'        
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - PYTHONPATH='/usr/src/app/drjobel/'

