version: '3.3'

services:
  streamlit:
    container_name: streamlit-multistage
    build:
      dockerfile: ./Dockerfile
      context: ./
    #:0.1.0
    image: streamlit-multistage   
    ports:
      - '8501:8501'
    volumes:
      - './data:/usr/src/app/data:delegated'
      - './project:/usr/src/app/project:delegated'
      - './images:/usr/src/app/images:delegated'
      - '/home/jobel/drjobel/opencode/:/usr/src/app/opencode:delegated'        
      # /venv/lib/python3.8/site-packages/
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - PYTHONPATH='/usr/src/app/opencode/'

