name: aqua
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - geopandas
  - geopy
  - streamlit
  - rasterio
  - scipy
  - rasterstats >=0.9
  - scikit-learn
  - folium
  # geoPandas to raster
  - geocube  
  - gdal
  # - pywedge (quick-plotting EDA)
  - pytest
  - pip
  - conda-pack
  # useful for quickly adding base maps
  - contextily
  - geoplot
  # Use for modelling with sklearn
  - xgboost
  - plotly
  # to keep context and run flows
  - prefect
  - python-graphviz
  - h3-py
  # - gdown # no need
  - altair
  - hiplot
  # https://geopandas.org/gallery/plotting_with_geoplot.html
  - mapclassify  # used by geoplot
  - geoplot
  # Context geo tiles in Python
  # https://contextily.readthedocs.io/en/latest/intro_guide.html
  - contextily
  - basemap
  - basemap-data-hires
  # https://towardsdatascience.com/real-time-visualization-of-google-form-responses-in-streamlit-1e7fd20c6574
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  - oauth2client
  - gspread
  - pip:
    - s2sphere    
    - pyimpute
    - turpy >= 0.2.9
    - blockdiag
    # - streamlit-folium  #this is causing problems with conda as it tries to install folium again. But different version
    - tinydb
    # SQLite
    - dataset
    - handsdown
       
        
    
