name: aqua
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - geopandas
  - geopy
  - streamlit
  - rasterio
  - scipy
  - rasterstats >=0.9
  - scikit-learn
  - folium
  # geoPandas to raster
  - geocube  
  - gdal
  # - pywedge (quick-plotting EDA)
  - pytest
  - pip
  - conda-pack
  # useful for quickly adding base maps
  - contextily
  - geoplot
  # Use for modelling with sklearn
  - xgboost
  - plotly
  # to keep context and run flows
  - prefect
  - python-graphviz
  - pip:
    - pyimpute
    - turpy >= 0.2.6
    - blockdiag
    - streamlit-folium
    - tinydb
    # SQLite
    - dataset
    - handsdown
